begin;
alter table books add column created_at timestamptz not null default now(), add column language text not null default 'und', add column genres text[] not null default '{}', add column series text, add column volume numeric check(volume > 0), add column status text not null default 'published' check(status in ('draft','published'));
alter table books alter column status set default 'draft';
alter table chapters add column created_at timestamptz not null default now();
alter table sections add column created_at timestamptz not null default now(), add column status text not null default 'published' check(status in ('draft','published')), add column draft_markdown text;
alter table sections alter column status set default 'draft';
create table authors (id uuid primary key default gen_random_uuid(), name text not null unique, bio text not null default '', photo_url text, created_at timestamptz not null default now());
create table book_authors (book_id uuid references books on delete cascade, author_id uuid references authors on delete cascade, primary key(book_id,author_id));
insert into authors(name) select distinct author from books where author is not null and trim(author) <> '';
insert into book_authors select b.id,a.id from books b join authors a on a.name=b.author;
create table users (id uuid primary key default gen_random_uuid(), email text not null unique, name text not null, password_hash text not null, role text not null default 'reader' check(role in ('reader','editor')), created_at timestamptz not null default now());
create table sessions (token_hash text primary key, user_id uuid not null references users on delete cascade, expires_at timestamptz not null);
create table reading (user_id uuid references users on delete cascade, book_id uuid references books on delete cascade, section_id uuid references sections on delete set null, updated_at timestamptz not null default now(), primary key(user_id,book_id));
create table shelves (user_id uuid references users on delete cascade, book_id uuid references books on delete cascade, favorite boolean not null default false, wishlist boolean not null default false, rating int check(rating between 1 and 5), review text not null default '', primary key(user_id,book_id));
create table annotations (id uuid primary key default gen_random_uuid(), user_id uuid not null references users on delete cascade, section_id uuid not null references sections on delete cascade, kind text not null check(kind in ('bookmark','highlight','note')), quote text not null default '', note text not null default '', created_at timestamptz not null default now());
create table revisions (id uuid primary key default gen_random_uuid(), section_id uuid not null references sections on delete cascade, user_id uuid references users on delete set null, title text not null, blocks jsonb not null, markdown text, created_at timestamptz not null default now());
alter table content_blocks add column created_at timestamptz not null default now();
alter table figures add column created_at timestamptz not null default now();
alter table tables add column created_at timestamptz not null default now();
alter table glossary_terms add column created_at timestamptz not null default now();
alter table symbols add column created_at timestamptz not null default now();
create index annotations_owner_idx on annotations(user_id,section_id);
create index revisions_section_idx on revisions(section_id,created_at desc);
commit;
